### ISSUE TITLE
Missing value for JSONP callback.

### ISSUE THREAD

**Issue by tristandunn** [rack/rack-contrib#100]
The JSONP middleware will raise a `NoMethodError` when the callback is `nil` from the [`has_callback?`](https://github.com/rack/rack-contrib/blob/c624e1ae4390667e355a7467632b5228716ba551/lib/rack/contrib/jsonp.rb#L67-L69) method. You can recreate it if you provide a `?callback` query string.

I had issues getting the tests running locally, so I'm currently monkey patching it with an added `to_s`:

```ruby
require "rack/contrib/jsonp"

module Rack
  class JSONP
    def has_callback?(request)
      request.params.include?("callback") and not request.params["callback"].to_s.empty?
    end
  end
end
```

**Comment by mpalmer** [comment]
The test suite in master should be a whole lot easier to get along with now, if you'd like to take another stab at it.

**Comment by tristandunn** [comment]
@mpalmer Thanks for the heads up. It was a breeze this time.

**Comment by jjb** [comment]
:fireworks:
