### ISSUE TITLE
The value and future of Rack::StaticCache

### ISSUE THREAD

**Issue by jjb** [rack/rack-contrib#109]
Rack::StaticCache is sort of reinventing the wheel of middleware that is done better elsewhere. But it's also the sort of thing that is a good candidate to be maintained in rack-contrib (have a good implementation of a widely-used and relatively small feature).

Consider the rails static middleware, https://github.com/rails/rails/blob/master/actionpack/lib/action_dispatch/middleware/static.rb. It is has been actively developed and seems to have identical features and more, and doesn't seem to be rails-specific.

We could...

1. drop our middleware because it's redundant with rails's (bad option, because then people would have to require action_dispatch in their non-rails projects.)
2. consider taking ideas from it
3. copy it entirely because it's better
 a. also submit a patch to rails to use ours for rails 5
 b. a, but put it into rack propper instead of rack-contrib

TBH I haven't thought through if Rack::StaticCache is actually doing anything poorly. But it just seems like the sort of thing that should be well-done by rack-contrib and used in many other places, so I wanted to start a conversation.

**Comment by mpalmer** [comment]
There does seem to be a reasonable amount of overlap between the `ActionDispatch::FileHandler` middleware and `Rack::StaticCache`, but it's far from a drop-in replacement.  `FileHandler`, for instance, does both caching *and* compression.  I'd not be averse to handing `StaticCache` over to `rack` core, although @raggi's comments in #104 suggests that it would be better to split it out into a separate `rack-middleware-static` gem.

For now, I think we should leave it where it is, and discuss with `rack` core a longer-term reorg of the contents of both `rack` and `rack-contrib` into an entirely new packaging structure, to be executed in a 2.0 release series (for both `rack` and `rack-contrib`.
