### ISSUE TITLE
rack/contrib assumes a git repository context

### ISSUE THREAD

**Issue by svenfuchs** [rack/rack-contrib#122]
It seems this https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib.rb#L2 now always assumes a Git repository to be present, and fails otherwise.

Is rack/contrib not supposed to work outside of the context of a Git repository any more? 

We do have a Sinatra app which is being packaged and shipped outside of a Git repository, and upgrading rack/contrib fails.

**Comment by rkh** [comment]
I also have to add that I'm quite surprised two runtime dependencies (git and git-version-bump) were added to set a static string value.

**Comment by sashaegorov** [comment]
Subscribe

**Comment by lksv** [comment]
linking with #126

**Comment by stefan-kolb** [comment]
+1

**Comment by mpalmer** [comment]
It was never a deliberate intention to only support git repository contexts (well, and gems), but `git-version-bump` is no longer a runtime dependency, so whatever problem you were seeing might be gone now.
