### ISSUE TITLE
Rack::JSONP::VALID_JS_CHARS missing brackets and quotes

### ISSUE THREAD

**Issue by naliwajek** [rack/rack-contrib#123]
Hello,

I'm using callback from [Pusher](http://pusher.com) in my app: `Pusher.auth_callbacks['1']` and it is currently invalid:

``` ruby
Rack::JSONP::VALID_CALLBACK =~ "Pusher.auth_callbacks['1']"
=> nil
```

Is there a reason why `[`, `]`, `'` and `"` aren't allowed?

Overriding this isn't much of a pain but it takes some time to debug it. I'll be happy to submit a PR if possible. 

Cheers.

**Comment by mpalmer** [comment]
A PR, with tests, would be appreciated.  I have no direct experience with JSONP, so I really have no idea what the answer is.
