### ISSUE TITLE
Doesn't including git-version-bump gem violates MIT license?

### ISSUE THREAD

**Issue by lksv** [rack/rack-contrib#125]
it is included `git-version-bump` in `rack-contrib.gemspec` file and therefore it is part of any project which rack-contrib use.
Gem `git-version-bump` is GPL v3. I'm not layer but I guess that this may violates the GPL license of this gem.

Is here anyone who can confirm or disprove it?

**Comment by chneukirchen** [comment]
This library is only used during building the gem, and not when using the library... the licenses can be orthogonal.

**Comment by lksv** [comment]
@chneukirchen 
I consulted it and it really seems that it is license violation. It is used in https://github.com/rack/rack-contrib/blob/ea0c82dc3a6353542b7fe0cbd262c43378e28b31/lib/rack/contrib.rb#L7 which is part of the gems public api.

It is necessary to remove usage from `rack-contrib/lib/rack/contrib.rb` file and use `s.add_development_dependency` in https://github.com/rack/rack-contrib/blob/master/rack-contrib.gemspec#L38

**Comment by chneukirchen** [comment]
You are right, the library should not use this function.

@mpalmer you introduced this dependency (and I see you are the autor of the module in question as well)... can you remove the runtime dependency, or relicense git-version-bump so we can use it unencumbered?

**Comment by mpalmer** [comment]
I'll pull gvb out as a runtime dependency.

**Comment by nishantmodak** [comment]
The wiki is maintained by the community. So if there aren't any up to date instructions, we recommend you to explore the solution yourself and hopefully contribute your findings back!

**Comment by chneukirchen** [comment]
@mp

**Comment by mpalmer** [comment]
Fixed by #114.
