### ISSUE TITLE
Support Rack 2.0

### ISSUE THREAD

**Issue by joevandyk** [rack/rack-contrib#127]
Rack 2.0 is out!

**Comment by seanhandley** [comment]
`rack-contrib` fails with Rails 5 and Rack 2:

```
$ bundle exec rails c
/Users/sean/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/rack-contrib-1.2.0/lib/rack/contrib/sendfile.rb:5:in `<class:File>': undefined method `path' for class `Rack::File' (NameError)
```

**Comment by xn** [comment]
+1

**Comment by xn** [comment]
Btw: https://github.com/kannanr/rack-contrib
has some work on this.

**Comment by atomless** [comment]
+1

**Comment by atomless** [comment]
Any rough timeline on this ?

**Comment by dmitry** [comment]
Why not to merge rack-contrib into a rack core?

**Comment by rastating** [comment]
+1 for this

**Comment by atomless** [comment]
Pleeeeeease can this be merged? https://github.com/rack/rack-contrib/pull/129

**Comment by robertsonsamuel** [comment]
Can we merge this in please! Would love to use this with Grape and rails 5!

**Comment by codeblooded** [comment]
Would like to #bump this...

**Comment by gonace** [comment]
I like to #bump this as well...

**Comment by mpalmer** [comment]
Closing in favour of PR #129.

**Comment by kinyodan** [comment]
so what was the solution for this ? having the same problem 

 rake aborted!
remote:        NameError: undefined method `path' for class `Rack::File'
remote:        /tmp/build_3bfc33bbb516ee7bd26a6ab3bfeab613/vendor/bundle/ruby/2.3.0/gems/rack-contrib-1.2.0/lib/rack/contrib/sendfile.rb:5:in `<class:File>'

**Comment by seanjhulse** [comment]
bump same issue

**Comment by seanjhulse** [comment]
For people that need a quick fix to this problem. This fork worked in my Gemfile:

`gem "rack-contrib", git: 'https://github.com/sshaw/rack-contrib.git', branch: 'rack-2.0', require: 'rack/contrib'`
