### ISSUE TITLE
bytesize issues

### ISSUE THREAD

**Issue by znz** [rack/rack-contrib#148]
I think https://github.com/rack/rack-contrib/blob/7fd98fc0b8b7feeb863743c93ab13f15b221c920/lib/rack/contrib/jsonp.rb#L109 and https://github.com/rack/rack-contrib/blob/7fd98fc0b8b7feeb863743c93ab13f15b221c920/lib/rack/contrib/post_body_content_type_parser.rb#L42 have same problem of https://github.com/rack/rack-contrib/issues/143 .
And https://github.com/rack/rack-contrib/blob/7fd98fc0b8b7feeb863743c93ab13f15b221c920/lib/rack/contrib/csshttprequest.rb#L34 maybe too.

**Comment by mpalmer** [comment]
That does seem very plausible.
