### ISSUE TITLE
Rack::Locale doesn't match languages with variants

### ISSUE THREAD

**Issue by jlecour** [rack/rack-contrib#151]
If my browser sends locales with variants (`fr-fr`, `fr-ca`, `en-us`, `en-gb`…) they don't match available locales that are generally set with just 2 characters (`fr`, `en`…).

```
> I18n.available_locales
=> [:en, :fr]

> languages_and_qvalues
=> [["fr-fr", "1.0"]]

> I18n.locale
=> :en
```

It's possible to match like this … 
```ruby
language_and_qvalue = languages_and_qvalues.sort_by { |(locale, qvalue)|
  qvalue.to_f
}.reverse.detect { |(locale, qvalue)|
  if I18n.enforce_available_locales
    locale == '*' \
      || I18n.available_locales.include?(locale.to_sym) \
      || I18n.available_locales.include?(locale[0,2].to_sym)
  else
    true
  end
}
```
 … but the `detect` method returns the current element `fr-ch` which is not valid for `I18n.locale`.

We could truncate the return `lang` to the first 2 characters, but it would break when `fr-ch` is an available language with higher precedence than `fr-fr` or plain `fr`.

**Comment by rodrigoassis** [comment]
I'd love to have this feature as well. Is there any other way to do this?

**Comment by rodrigoassis** [comment]
Created a **not pretty** PR for this. Happy to refactor. Let me know what you think :)
