### ISSUE TITLE
Rack::ResponseCache wrongly uses 'Content-Type' case-sensitively

### ISSUE THREAD

**Issue by utrenkner** [rack/rack-contrib#155]
I just ran into the following problem with ResponseCache: To ensure that only (x)html and css files are cached, the Content-Type of the response is tested. To this end it checks for [res[1]['Content-Type']](https://github.com/rack/rack-contrib/blob/master/lib/rack/contrib/response_cache.rb#L18). But the header fields of the resource I was trying to cache were in lower-case: "content-type" and thus the test failed.

RFC 7230 says that the [names of header fields are case-insensitive](https://tools.ietf.org/html/rfc7230#section-3.2). Therefore we need to make sure that different casing is allowed in ResponseCache. 

As I am still new to Rack and Ruby, I do not know, if a specific function exists for such header fields. As a sufficient fix one could test if res[1]['Content-Type'] existed and else use res[1]['content-type']. I think it is rather unlikely to find other legal versions such as 'cOnTeNt-TyPe'.

**Comment by mpalmer** [comment]
The usual solution to this is case-normalisation -- applying a transformation to the strings before their use as a key to ensure that no matter what case the characters were in originally, they'll be in the same case when they're used as a key.  Jamming a `.downcase` on the end of them all would do the trick.

**Comment by chrisfrank** [comment]
Hey @mpalmer and @utrenkner,

I'm willing to file a PR to fix this, but first, can one of you help me understand what this middleware does? It looks like it writes to a cache on each matching GET request. But I don't see it ever trying to _read_ from the cache. Unless something earlier in the request handling cycle is checking the cache and returning early on a hit, it seems like `Rack::ResponseCache` would just slow down every matching request by adding a useless write. If this indeed the intended behavior, I'd like to make the usage docs explicitly state that it should be mounted after a cache-reading middleware or behind a proxy.

**Comment by mpalmer** [comment]
Based purely on the middleware description (specifically the analogy to Rails page caching), my expectation is that pages cached by this middleware are supposed to be served directly by the frontend webserver, such as via nginx's `try_files` directive.  Extending the documentation to make that clear would be a definite improvement.

(In case you're wondering, I didn't write any of the middleware in `rack-contrib`, I just try to keep the lights on around here)

**Comment by utrenkner** [comment]
@chrisfrank Yes, you are correct, ``Rack::ResponseCache`` only caches successful GET requests with no query string. I was looking for exactly this functionality - the rest of the logic (deciding whether or not a cached file is served, and cache invalidation will be provided by other pieces).

The comment at the beginning of the file explains its use case very well and I think you can almost copy&paste this text to any usage documentation.

**Comment by chrisfrank** [comment]
A heartfelt thanks for keeping the lights on, @mpalmer. And thanks, both of you, for answering my question. I'll submit a PR for this today.
