### ISSUE TITLE
Please add a CHANGELOG

### ISSUE THREAD

**Issue by alainravet** [rack/rack-contrib#156]
I've just ran my weekly `bundle outdated`, and it signalled 9 gems are outdated in one of my project.
One by one, I reviewed 7 changelogs and updated 7 gems.
The other 2 have no changelogs, so I had to review every single new commit comment, and sometimes diff.
A pain in the keyboard and too much wasted time.
It shouldn't be that way.

**Comment by mpalmer** [comment]
Feel free to be the change you wish to see in the world.

**Comment by alainravet** [comment]
@mpalmer Look around: updating the changelog is not an after the fact action; it's like refactoring: part of the standard work, by the person who implemented the change.

**Comment by mpalmer** [comment]
Look around: every rack-contrib release has [release notes](https://github.com/rack/rack-contrib/releases).
