### ISSUE TITLE
How to make rspec run config.ru?

### ISSUE THREAD

**Issue by obromios** [rack/rack-contrib#161]
I am using ```Rack::Locale``` in my app, and it works well in development, thank you.

However, I would like to test its effect on the app using ```rspec``` request specs. It looks like ```rspec``` does not load ```config.ru```. Is there any way of around this, such as putting some code in ```config/environments/test.rb```?  I have asked this [question](https://stackoverflow.com/questions/56606013/how-to-make-rspec-load-config-ru) on SO but received no answer.

**Comment by mpalmer** [comment]
It doesn't look like you're reporting an issue in a rack-contrib middleware.  Please re-open and provide further information about the functional deficiency if this is incorrect.
