### ISSUE TITLE
Passing a block to PostBodyContentTypeParser fails

### ISSUE THREAD

**Issue by pjmartorell** [rack/rack-contrib#162]
Hi! I'm using Sinatra and I'm trying to pass a block to `PostBodyContentTypeParser` like the following to parse body as a symbolized hash but I'm struggling:

```ruby
# middleware to parse JSON post body as a symbolized hash
use(Rack::PostBodyContentTypeParser) { proc { |body| JSON.parse(body, symbolize_names: true, create_additions: false) } }
```
I'm not sure if it's a problem of Sinatra or `Rack::PostBodyContentTypeParser`, but I noticed it gets fixed if I add an additional `call`  to `@block.call(body)` in `PostBodyContentTypeParser#call(env)` like the following:
```ruby
  class PostBodyContentTypeParser
     ...
    def call(env)
      if Rack::Request.new(env).media_type == APPLICATION_JSON && (body = env[POST_BODY].read).length != 0
        env[POST_BODY].rewind # somebody might try to read this stream
        env.update(FORM_HASH => @block.call.call(body), FORM_INPUT => env[POST_BODY])
      end
      @app.call(env)
    rescue JSON::ParserError
      bad_request('failed to parse body as JSON')
    end
```
The problem is that `@block.call(body)` returns my Proc instead of returning the result of calling the Proc.

**Comment by pjmartorell** [comment]
After trial & error I solved the issue like the following:
```ruby
  proc = proc { |body| JSON.parse(body, symbolize_names: true, create_additions: false) }
  use Rack::PostBodyContentTypeParser, &proc
```
I don't know if it's supposed to be like this but it just works.

**Comment by mpalmer** [comment]
A PR correcting either the code or the documentation would be appreciated.
