### ISSUE TITLE
Get rid of tmail dependency....

### ISSUE THREAD

**Issue by virtualfunction** [rack/rack-contrib#19]
TMail is a nasty turd pile of poop ;-)

Rack::MailExceptions should be updated to use the new mail gem like ActionMailer 3.x uses. It's a fairly simple fix (I've got a monkey patched version... I can clean it up and update the tests and throw over a pull request).

The main reason for the dependency change is that many Ruby 1.9 users will have issues with TMail (unless they are using the hacked version shipped in in ActionMailer 2.x). The new mail gem works fine on all Ruby versions and with many people now migrating to Rails 3.x and Ruby 1.9 it makes sense to update this. 

While ExceptionNotifier exists, it's Rack support was added as an afterthought, and depending on bits of Rails which is not good for users of Sinatra, etc. Further more ExceptionNotifier is not maintained and thus if Rack::MailExceptions was updated, it would be good to encourage users to migrate to it as this works seamlessly across all Rack apps.

**Comment by mpalmer** [comment]
TMail is dead.  Long live Mail!
