### ISSUE TITLE
Testing instructions in the README are somewhat out of date

### ISSUE THREAD

**Issue by mpalmer** [rack/rack-contrib#196]
As discussed in #195, the README gives instructions for local testing that are, to the say the least, ancient.  They need to be updated to match both the Ruby versions we actually support, and modified so that they work.

**Comment by ioquatix** [comment]
I agree. If you have time to make a PR, that would be awesome.

**Comment by ioquatix** [comment]
Fixed by https://github.com/rack/rack-contrib/pull/197
