### ISSUE TITLE
StaticCache should allow less than one year expiration

### ISSUE THREAD

**Issue by niko** [rack/rack-contrib#32]
As the cache_duration is given in years it's possible to pass a fraction of a year as :duration parameter, for example 1/365 for one day. But then the Cache-Control header will look like this:

Cache-Control: max-age=86400.0, public

I suggest modifying duration_in_seconds from this

<pre><code>def duration_in_seconds
  60 * 60 * 24 * 365 * @cache_duration
end</code></pre>

to this

<pre><code>def duration_in_seconds
  (60 * 60 * 24 * 365 * @cache_duration).to_i
end</code></pre>

**Comment by mpalmer** [comment]
Looks like this got fixed in 46d85e4 but this issue wasn't closed at the time.
