### ISSUE TITLE
Add times parameter support for Rack::Profiler

### ISSUE THREAD

**Issue by mperham** [rack/rack-contrib#49]
Rack::Profiler allows you to set a times parameter globally:

    use Rack::Profiler, :times => 100

but this is not granular enough.  Some of my pages take 1ms to render, others take 1s.  I want to give the times count as part of the URL so I can tune the count per page:

    /some_long_page?profile=cpu_time&times=10
    /quick?profile=cpu_time&times=10000

**Comment by mpalmer** [comment]
Closing this in favour of #52.
