### ISSUE TITLE
Rack::StaticCache should set a Date header

### ISSUE THREAD

**Issue by niedfelj** [rack/rack-contrib#58]
Webkit based browsers still report in Audit panel items are uncacheable, added a Date header and they then respond correctly.  Seems this should be part of the StaticCache?

**Comment by mpalmer** [comment]
It should be part of *something*, and given that the middleware is doing the date dance already, I suppose it should be adding `Date`, too.

**Comment by jjb** [comment]
I think I have experienced the problem of a missing Date header on a previous project of mine. I can look into the reasons and research I did for that.

If we decide in #84 that we are keeping StaticCache I can pick this up.

**Comment by mpalmer** [comment]
I'm quite confident that it's a problem to not have the `Date` header; without it, a client can't be confident that it has the right idea of what "the time" is from the server's perspective.  Sure, plenty of caches / UAs will assume their time is correct if no `Date` header is provided, but some don't.

More than happy for you to take it, @jjb.
