### ISSUE TITLE
JSONP body and headers

### ISSUE THREAD

**Issue by jbarreneche** [rack/rack-contrib#69]
Currently, with the JSONP Middleware the client can only retrieve the body of the response (unable to get other headers information)

We are using a customized version of this middleware to get the same structure that [Github API](http://developer.github.com/v3/#json-p-callbacks) uses.

```
foo({
  "meta": {
    "status": 200,
    "X-RateLimit-Limit": "5000",
    "X-RateLimit-Remaining": "4966",
    "Link": [ // pagination headers and other links
      ["https://api.github.com?page=2", {"rel": "next"}]
    ]
  },
  "data": {
    // the data
  }
})
```

If you think this could be useful to others I can make the Pull Request.

Obviously, the main problem would be compatibility. So I was thinking adding some configuration:

```
use Rack::JSONP, format: :body_and_headers
```

The default would work with the current formatting/padding and the new option would use the  other structure.

WDYT?

**Comment by mpalmer** [comment]
I think I'd like to see that PR, if you've still got it around.
