### ISSUE TITLE
Rack::Locale strips the culture part of the string, which is useful in some cases

### ISSUE THREAD

**Issue by rares** [rack/rack-contrib#7]
In cases where you would want to display culture specific formatting (like currency between en-US and en-GB) Rack::Locale isn't entirely useful. 

In this branch -> http://github.com/rares/rack-contrib/branches/locale_add_full_culture I added some non-default behavior that leaves the culture part of the string intact (so es-MX instead of es). 

Also built up the test suite around Rack::Locale a bit. 

I apologize for sending a pull request earlier and now this; Just wasn't sure of the contribution policy.

**Comment by mpalmer** [comment]
The referenced repo is gone.  I can't find a previous PR.  I'm going to close this off.  @rares, if you can resurrect your repo and put in a new PR, I'll be happy to take a look at it.

**Comment by rares** [comment]
Looks like this was taken care of in a790c26e974cf3925b6f0f0ed0e92e9a332c1169 in a similar manner

**Comment by mpalmer** [comment]
@rares, thanks for the confirmation.

**Comment by jjb** [comment]
:clap: @rares for providing that info
