### ISSUE TITLE
Project is orphaned - please mark as such

### ISSUE THREAD

**Issue by mipearson** [rack/rack-contrib#72]
I have two pull requests pending, neither has been actioned for five months.

**Comment by jjb** [comment]
@leahneukirchen thanks!

@guss77 @mpalmer should we work our way through existing PRs, with all 3 of us reviewing?

maybe for the time being we'll say we only merge when we have unanimous consensus? and if this becomes a problem we can amend the policy?

we can start with @mipearson's PRs.

**Comment by jjb** [comment]
@leahneukirchen looks like you didn't add me (from your comment above seems like you meant to)

**Comment by jjb** [comment]
@leahneukirchen nevermind, saw the invite now! all good.
