### ISSUE TITLE
JSONP shouldn't change content type in place.

### ISSUE THREAD

**Issue by samleb** [rack/rack-contrib#9]
JSONP uses `gsub!` to change content type. It may have the side effect of changing `Rack::Mime::MIME_TYPES['.json']` in place when used, for instance, with Sinatra's `content_type :json`.

It can be [fixed](http://github.com/samleb/rack-contrib/commit/2921c9e78b6c473d5d42162a2c33ac90773ce291) by using `gsub` instead.

**Comment by mpalmer** [comment]
This appears to have been fixed in 47661faf9 but this issue was never subsequently closed.
